---
- hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: "Create VPC and Networking Components"
      include_role:
        name: vpc

    - name: "Install and Configure Jenkins"
      include_role:
        name: jenkins

    - name: "Build and Push Docker Image"
      include_role:
        name: docker
      vars:
        github_repo_url: "https://github.com/amar-m-cloud/Django-Notes-Application.git"
        docker_hub_username: "amar-m-cloud"
        docker_hub_password: "Amar@796272"

    - name: "Deploy Docker Image on Kubernetes"
      include_role:
        name: kubernetes
