---
- name: Create VPC
  ec2_vpc:
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    resource_tags:
      Name: "{{ vpc_name }}"
  register: vpc

- name: Create Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
  register: igw

- name: Create Public Subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ public_subnet_cidr }}"
    map_public: true
  register: public_subnet

- name: Create Route Table for Public Subnet
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    subnet_id: "{{ public_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gw_id: "{{ igw.gateway_id }}"
